# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 05:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_History',
            fields=[
                ('university_roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('S1', 'Semester I'), ('S2', 'Semester II'), ('S3', 'Semester III'), ('S4', 'Semester IV'), ('S5', 'Semester V'), ('S6', 'Semester VI'), ('S7', 'Semester VII'), ('S8', 'Semester VIII')], default=1, max_length=50)),
                ('month_of_registration', models.DateField()),
                ('Whether_condonation_availed', models.CharField(choices=[(1, 'No'), (2, 'Yes')], default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('hours_in_total', models.IntegerField()),
                ('hours_attended', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('ADHOC', 'ADHOC')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaches_at', to='insy.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('semester', models.CharField(choices=[('S1', 'Semester I'), ('S2', 'Semester II'), ('S3', 'Semester III'), ('S4', 'Semester IV'), ('S5', 'Semester V'), ('S6', 'Semester VI'), ('S7', 'Semester VII'), ('S8', 'Semester VIII')], default=1, max_length=50)),
                ('date_of_registration', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('name_of_parent', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('Whether_eligible_for_registration', models.CharField(choices=[(1, 'No'), (2, 'Yes')], default=2, max_length=50)),
                ('Hosteler_or_dayscholar', models.CharField(choices=[('D', 'Dayscholar'), ('H', 'Hosteler')], default='D', max_length=10)),
                ('name_of_hostel', models.CharField(blank=True, max_length=50, null=True)),
                ('Academic_History', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examdetails', to='insy.Academic_History')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_in', to='insy.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to='insy.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attends', to='insy.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attended', to='insy.Subject'),
        ),
    ]
