# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insy', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Hosteler_or_dayscholar',
            field=models.CharField(choices=[('D', 'Dayscholar'), ('H', 'Hosteler')], default='D', max_length=50),
        ),
    ]
