# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insy', '0003_student_hosteler_or_dayscholar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Commmunication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('PE', 'Production Engineering')], default='CSE', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='name_of_hostel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Hosteler_or_dayscholar',
            field=models.CharField(choices=[('D', 'Dayscholar'), ('H', 'Hosteler')], default='D', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to='insy.Faculty'),
        ),
    ]
