# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insy', '0004_auto_20170414_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
    ]
